# 1342676582:AAGchMbACSSiZsQFUBhHnZiojyrqEqwGL-A

development: &dev # secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  telegram:
    bot:
      token: <%= ENV['TELEGRAM_BOT_TOKEN'] %>
      username: <%= ENV['TELEGRAM_BOT_NAME'] %>
      # async: true

test:
  # secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  telegram:
    bot:
      token: ENV['TELEGRAM_BOT_TOKEN']
      username: ENV['TELEGRAM_BOT_NAME']
      # async: true

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *dev
